name: "Check with Bulloak that Solidity tests conform to BTT spec"

on:
  workflow_call:
    inputs:
      skip-modifiers:
        default: true
        required: false
        type: "boolean"

      test-dir:
        default: "tests/**/**.tree"
        required: false
        type: "string"

      working-directory:
        default: "."
        required: false
        type: "string"

jobs:
  bulloak-check:
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Install and run Bulloak"
        uses: "smol-ninja/bulloak-toolchain@v2"
        with:
          skip-modifiers: ${{ inputs.skip-modifiers }}
          test-dir: ${{ inputs.test-dir }}

      - name: "Bulloak summary"
        run: | # shell
          echo "## Bulloak Check result" >> $GITHUB_STEP_SUMMARY
          echo "âœ… Passed" >> $GITHUB_STEP_SUMMARY
